language: csharp
solution: CpfValidation.sln

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
    - mono: latest
script:
  - xbuild /p:Configuration=Release CpfValidation.sln
  - dotnet run ./luca16s/CpfValidation/CpfTest/Program.cs
